services:
  - type: web
    name: expense-tracker
    runtime: docker
    plan: free
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: SPRING_DATA_MONGODB_URI
        sync: false
      - key: SPRING_DATA_MONGODB_DATABASE
        value: expense_tracker
      - key: JWT_SECRET_KEY
        generateValue: true
